# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- name: 167 remote ssh commands using password
    #  uses: appleboy/ssh-action@v0.1.8
     # with:
     #   host: ${{ secrets.HOST }}
      #  username: ${{ secrets.USERNAME }}
       # password: ${{ secrets.PASSWORD }}
   #     port: ${{ secrets.PORT }}
     #   script: |
    #      git clone https://github.com/masterkube/axonlogs.git
    #      cd axonlogs
     #     sudo apt install python3-pip
    #      pip install -r requirements.txt
       #   nohup python3 dockercmd.py &
          
    - name: 137 remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD2 }}
        port: ${{ secrets.PORT }}
        script: |
          git clone https://github.com/masterkube/axonlogs.git
          cd axonlogs
          sudo apt install python3-pip
          pip install -r requirements.txt
          nohup python3 dockercmd.py &
